language: android
sudo: false
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-27.0.1
    - android-27
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'
before_install:
  - chmod +x gradlew
  - git submodule update --init --recursive
install:
  - ./gradlew
script:
  - ./gradlew :sample:assembleDebug --stacktrace
  - ./gradlew :mezzanine-compiler:test --stacktrace
  - ./gradlew jacocoTestReport --stacktrace
after_success:
  - bash <(curl -s https://codecov.io/bash)